name: eduva-${APP_ENV}
services:
  eduva-coredev: # a changer
    build:
      target: ${APP_ENV}
      context: ..
      dockerfile: docker/Dockerfile
    container_name: eduvacore_${APP_ENV} # a changer
    image: eduvacore:${APP_ENV} # a changer
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-nseven"
      - "traefik.http.routers.eduva-coredev.rule=${HOST_TRAEFIK}"
      - "traefik.http.routers.eduva-coredev.entrypoints=websecure"
      - "traefik.http.routers.eduva-coredev.tls=true"
      - "traefik.http.routers.eduva-coredev.tls.certresolver=default"
      - "traefik.http.services.eduva-coredev.loadbalancer.server.port=${PORT}"
      - "traefik.http.services.eduva-coredev.loadbalancer.server.scheme=http"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    networks:
      - traefik-nseven
      - eduva
    depends_on:
      - eduva-coredev-db # a changer

  eduva-coredev-db: # a changer
    image: mongo:7
    container_name: eduvacore_${APP_ENV}_db # a changer
    restart: unless-stopped
    volumes:
      - eduvacore_dev_db:/data/db # a changer
      - ../docker/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT_EX:-27017}:27017"
    networks:
      - traefik-nseven
      - eduva

networks:
  traefik-nseven:
    external: true
  eduva:
    driver: bridge

volumes:
  eduvacore_dev_db: # a changer doit correspondre au volume de la DB